name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # manually creating data
    - model: mysite.user
      pk: 5432
      fields:
        is_tutor: 0
        is_student: 1
    - model: mysite.user
      pk: 5433
      fields:
        is_tutor: 1
        is_student: 0

    # unit testing
    - name: Uploads Correct Title
      run: |
        

    - name: Run Tests
      run: |
        python manage.py test


// add class
// searches class
// test if student or tutor exists